export const qs = [
['write-e11','SELECT · WHERE','easy','Write a query returning names of books with more than 300 pages.',
 'books',['id','title','pages'],[[1,'Rust',200],[2,'Fog',450],[3,'Halo',320],[4,'Mist',260]],
 ['title'],[['Fog'],['Halo']],false,
 'WHERE pages > 300.',
 'SELECT title FROM books WHERE pages > 300;'],
['write-e12','AND · OR','easy','Write a query that returns names of products in Office category priced 20 or less.',
 'products',['id','name','category','price'],[[1,'Pen','Office',5],[2,'Desk','Office',200],[3,'Clip','Office',10],[4,'Cup','Kitchen',15]],
 ['name'],[['Pen'],['Clip']],false,
 'category = \'Office\' AND price <= 20.',
 'SELECT name FROM products WHERE category = \'Office\' AND price <= 20;'],
['write-e13','LIKE','easy','Write a query that returns names of customers whose name starts with "Al".',
 'customers',['id','name'],[[1,'Alice'],[2,'Alan'],[3,'Bo'],[4,'Alex']],
 ['name'],[['Alice'],['Alan'],['Alex']],false,
 'WHERE name LIKE \'Al%\'.',
 'SELECT name FROM customers WHERE name LIKE \'Al%\';'],
['write-e14','ORDER BY · ASC','easy','Write a query listing names of cities ordered A to Z.',
 'cities',['id','name'],[[1,'Delhi'],[2,'Tokyo'],[3,'Agra']],
 ['name'],[['Agra'],['Delhi'],['Tokyo']],true,
 'ORDER BY name ASC.',
 'SELECT name FROM cities ORDER BY name ASC;'],
['write-e15','SUM','easy','Write a query that returns the total price of all products.',
 'products',['id','name','price'],[[1,'Pen',5],[2,'Desk',10],[3,'Cup',25]],
 ['total' ],[[40]],false,
 'SUM(price) with alias total.',
 'SELECT SUM(price) AS total FROM products;'],
['write-e16','AVG','easy','Write a query that returns the average price of all products.',
 'products',['id','name','price'],[[1,'Pen',5],[2,'Desk',10],[3,'Cup',15]],
 ['avg' ],[[10]],false,
 'AVG(price) with alias avg.',
 'SELECT AVG(price) AS avg FROM products;'],
['write-e17','SELECT · WHERE','easy','Write a query that returns the name and price of products priced 100 or more.',
 'products',['id','name','price'],[[1,'Pen',5],[2,'Desk',200],[3,'Lamp',100],[4,'Cup',90]],
 ['name','price'],[[ 'Desk',200],['Lamp',100]],false,
 'WHERE price >= 100.',
 'SELECT name, price FROM products WHERE price >= 100;'],
['write-e18','MIN','easy','Write a query that returns the cheapest product price.',
 'products',['id','name','price'],[[1,'Pen',5],[2,'Desk',200],[3,'Cup',10]],
 ['min' ],[[5]],false,
 'MIN(price) with alias min.',
 'SELECT MIN(price) AS min FROM products;'],
['write-e19','MAX','easy','Write a query that returns the highest salary among employees.',
 'employees',['id','name','salary'],[[1,'Ada',90000],[2,'Bo',60000],[3,'Ci',75000]],
 ['max' ],[[90000]],false,
 'MAX(salary) with alias max.',
 'SELECT MAX(salary) AS max FROM employees;'],
['write-e20','WHERE · IS NOT NULL','easy','Write a query returning names of customers that have a phone number.',
 'customers',['id','name','phone'],[[1,'Ada','555-1'],[2,'Bo',null],[3,'Ci','555-3']],
 ['name'],[['Ada'],['Ci']],false,
 'WHERE phone IS NOT NULL.',
 'SELECT name FROM customers WHERE phone IS NOT NULL;'],
['write-e21','DISTINCT','easy','Write a query returning each distinct city customers live in.',
 'customers',['id','name','city'],[[1,'Ada','NY'],[2,'Bo','LA'],[3,'Ci','NY']],
 ['city'],[['NY'],['LA']],false,
 'SELECT DISTINCT city FROM customers.',
 'SELECT DISTINCT city FROM customers;'],
['write-e22','SELECT · WHERE','easy','Write a query returning names of products priced between 10 and 20 inclusive.',
 'products',['id','name','price'],[[1,'Pen',5],[2,'Box',10],[3,'Cup',20],[4,'Desk',200]],
 ['name'],[['Box'],['Cup']],false,
 'BETWEEN 10 AND 20.',
 'SELECT name FROM products WHERE price BETWEEN 10 AND 20;'],
['write-e23','LIKE','easy','Write a query returning names of customers whose name ends with "a".',
 'customers',['id','name'],[[1,'Ada'],[2,'Bo'],[3,'Mina'],[4,'Rex']],
 ['name'],[['Ada'],['Mina']],false,
 'WHERE name LIKE \'%a\'.',
 'SELECT name FROM customers WHERE name LIKE \'%a\';'],
['write-e24','AND','easy','Write a query returning names of employees in Sales earning more than 45000.',
 'employees',['id','name','dept','salary'],[[1,'Ada','Sales',50000],[2,'Bo','Sales',40000],[3,'Ci','Eng',90000]],
 ['name'],[['Ada']],false,
 'WHERE dept = \'Sales\' AND salary > 45000.',
 'SELECT name FROM employees WHERE dept = \'Sales\' AND salary > 45000;'],
['write-e25','SELECT · WHERE','easy','Write a query returning the name and price of products not priced 10.',
 'products',['id','name','price'],[[1,'Pen',5],[2,'Cup',10],[3,'Desk',200]],
 ['name','price'],[[ 'Pen',5],['Desk',200]],false,
 'WHERE price <> 10 (or != 10).',
 'SELECT name, price FROM products WHERE price <> 10;'],
]
