export const qs = [
['write-e25','easy','SELECT · WHERE','Write a query returning names of products priced below 20.',
 'products',['id','name','price'],[[1,'Pen',5],[2,'Desk',200],[3,'Cup',10],[4,'Box',40]],
 ['name'],[['Pen'],['Cup']],false,'WHERE price < 20.',
 'SELECT name FROM products WHERE price < 20;'],
['write-e26','easy','SELECT · WHERE','Write a query returning names of items in stock (stock > 0).',
 'items',['id','name','stock'],[[1,'Pen',5],[2,'Desk',0],[3,'Cup',3]],
 ['name'],[['Pen'],['Cup']],false,'WHERE stock > 0.',
 'SELECT name FROM items WHERE stock > 0;'],
['write-e27','easy','SELECT · WHERE','Write a query showing name and price of products costing exactly 50.',
 'products',['id','name','price'],[[1,'Pen',5],[2,'Desk',50],[3,'Cup',50],[4,'Box',40]],
 ['name','price'],[[ 'Desk',50],['Cup',50]],false,'WHERE price = 50.',
 'SELECT name, price FROM products WHERE price = 50;'],
['write-e28','easy','DISTINCT','Write a query listing each distinct region where stores exist.',
 'stores',['id','name','region'],[[1,'A','North'],[2,'B','South'],[3,'C','North']],
 ['region'],[['North'],['South']],false,'SELECT DISTINCT region.',
 'SELECT DISTINCT region FROM stores;'],
['write-e29','easy','ORDER BY','Write a query returning product names, cheapest first.',
 'products',['id','name','price'],[[1,'Pen',5],[2,'Desk',200],[3,'Cup',10]],
 ['name'],[['Pen'],['Cup'],['Desk']],true,'ORDER BY price ASC.',
 'SELECT name FROM products ORDER BY price ASC;'],
['write-e30','easy','WHERE · comparison','Write a query returning names of employees aged 25 or older.',
 'employees',['id','name','age'],[[1,'Ada',25],[2,'Bo',19],[3,'Ci',30]],
 ['name'],[['Ada'],['Ci']],false,'WHERE age >= 25.',
 'SELECT name FROM employees WHERE age >= 25;'],
['write-e31','easy','WHERE · IS NULL','Write a query returning names of products with no serial number.',
 'products',['id','name','serial'],[[1,'Pen','S-1'],[2,'Gift',null],[3,'Cup','S-3'],[4,'Box',null]],
 ['name'],[['Gift'],['Box']],false,'WHERE serial IS NULL.',
 'SELECT name FROM products WHERE serial IS NULL;'],
['write-e32','easy','LIKE','Write a query returning names of products whose name contains "ed".',
 'products',['id','name'],[[1,'Red','N'],[2,'Signed','Y'],[3,'Cup','N']],
 ['name'],[['Signed']],false,"WHERE name LIKE '%ed%'.",
 'SELECT name FROM products WHERE name LIKE \'%ed%\';'],
['write-e33','easy','LIMIT','Write a query returning the names of only the first 2 products.',
 'products',['id','name'],[[1,'Pen'],[2,'Cup'],[3,'Desk'],[4,'Box']],
 ['name'],[['Pen'],['Cup']],true,'LIMIT 2.',
 'SELECT name FROM products LIMIT 2;'],
['write-e34','easy','COUNT','Write a query counting how many products exist.',
 'products',['id','name'],[[1,'Pen'],[2,'Cup'],[3,'Desk']],
 ['count'],[['3']],false,'SELECT COUNT(*).',
 'SELECT COUNT(*) FROM products;'],
]
