export const qs = [
    ['write-01', 'SELECT · WHERE', 'easy', 'Write a query that shows the name and salary of every employee earning more than $60,000.',
        'employees', ['id', 'name', 'salary'], [[1, 'Alice', 70000], [2, 'Bob', 50000], [3, 'Carol', 85000], [4, 'Dave', 45000], [5, 'Eve', 60000], [6, 'Frank', 62000]],
        ['name', 'salary'], [['Alice', 70000], ['Carol', 85000], ['Frank', 62000]], false,
        'Use WHERE salary > 60000. Eve earns exactly 60000, which is not more, so she is excluded.',
        'SELECT name, salary FROM employees WHERE salary > 60000;'],
    ['write-02', 'DISTINCT', 'easy', 'Write a query that lists every unique department exactly once.',
        'employees', ['id', 'name', 'dept'], [[1, 'Alice', 'Sales'], [2, 'Bob', 'Eng'], [3, 'Carol', 'Sales'], [4, 'Dave', 'Mkt']],
        ['dept'], [['Sales'], ['Eng'], ['Mkt']], false,
        'SELECT DISTINCT dept removes duplicate Sales.',
        'SELECT DISTINCT dept FROM employees;'],
    ['write-03', 'ORDER BY · LIMIT', 'easy', 'Write a query that returns the names of the 3 cheapest products, cheapest first.',
        'products', ['id', 'name', 'price'], [[1, 'Phone', 999], [2, 'Mouse', 20], [3, 'Keyboard', 50], [4, 'Monitor', 200], [5, 'Cable', 10]],
        ['name'], [['Cable'], ['Mouse'], ['Keyboard']], true,
        'ORDER BY price ASC then LIMIT 3.',
        'SELECT name FROM products ORDER BY price ASC LIMIT 3;'],
    ['write-e4', 'COUNT', 'easy', 'Write a query that counts how many employees there are.',
        'employees', ['id', 'name'], [[1, 'Ada'], [2, 'Bo'], [3, 'Ci']],
        ['count'], [[3]], false,
        'SELECT COUNT(*) AS count.',
        'SELECT COUNT(*) AS count FROM employees;'],
    ['write-e5', 'SELECT · WHERE', 'easy', 'Write a query that returns the names of products priced under 15.',
        'products', ['id', 'name', 'price'], [[1, 'Pen', 5], [2, 'Desk', 200], [3, 'Cup', 10], [4, 'Chair', 15]],
        ['name'], [['Pen'], ['Cup']], false,
        'Chair is exactly 15, not under 15.',
        'SELECT name FROM products WHERE price < 15;'],
    ['write-e6', 'ORDER BY · DESC', 'easy', 'Write a query listing the most expensive product first.',
        'products', ['id', 'name', 'price'], [[1, 'Pen', 5], [2, 'Desk', 200], [3, 'Cup', 10]],
        ['name'], [['Desk'], ['Cup'], ['Pen']], true,
        'ORDER BY price DESC.',
        'SELECT name FROM products ORDER BY price DESC;'],
    ['write-e7', 'WHERE · IS NULL', 'easy', 'Write a query returning the names of products that have no price.',
        'products', ['id', 'name', 'price'], [[1, 'Pen', 5], [2, 'Gift', null], [3, 'Cup', null]],
        ['name'], [['Gift'], ['Cup']], false,
        'WHERE price IS NULL (not = NULL).',
        'SELECT name FROM products WHERE price IS NULL;'],
    ['write-e8', 'SELECT · WHERE', 'easy', 'Write a query showing names of employees earning 50000 to 70000 inclusive.',
        'employees', ['id', 'name', 'salary'], [[1, 'Ada', 50000], [2, 'Bo', 70000], [3, 'Ci', 45000], [4, 'Dex', 65000]],
        ['name'], [['Ada'], ['Bo'], ['Dex']], false,
        'Use BETWEEN 50000 AND 70000 (inclusive).',
        'SELECT name FROM employees WHERE salary BETWEEN 50000 AND 70000;'],
    ['write-e9', 'DISTINCT', 'easy', 'Write a query that lists each distinct product category.',
        'products', ['id', 'name', 'category'], [[1, 'Pen', 'Office'], [2, 'Desk', 'Office'], [3, 'Cup', 'Kitchen']],
        ['category'], [['Office'], ['Kitchen']], false,
        'SELECT DISTINCT category FROM products.',
        'SELECT DISTINCT category FROM products;'],
    ['write-e10', 'SELECT · LIMIT', 'easy', 'Write a query that returns just the first 2 names from customers.',
        'customers', ['id', 'name'], [[1, 'Ada'], [2, 'Bo'], [3, 'Ci']],
        ['name'], [['Ada'], ['Bo']], true,
        'LIMIT 2.',
        'SELECT name FROM customers LIMIT 2;'],
]
