export const qs = [
['write-e35','easy','SELECT · WHERE','Write a query returning names of products with a price greater than the average price.',
 'products',['id','name','price'],[[1,'Pen',5],[2,'Desk',100],[3,'Cup',15],[4,'Lamp',60]],
 ['name'],[['Desk'],['Lamp']],false,
 'Subquery: WHERE price > (SELECT AVG(price) FROM products).',
 'SELECT name FROM products WHERE price > (SELECT AVG(price) FROM products);'],
['write-e36','easy','COUNT','Write a query returning the number of employees in the Sales department.',
 'employees',['id','name','dept'],[[1,'Ada','Sales'],[2,'Bo','Eng'],[3,'Ci','Sales']],
 ['count'],[['2']],false,
 'COUNT(*) with WHERE dept = \'Sales\'.',
 "SELECT COUNT(*) FROM employees WHERE dept = 'Sales';"],
['write-e37','easy','ORDER BY · DESC · LIMIT','Write a query returning the 3 highest-paid employee names, best first.',
 'employees',['id','name','salary'],[[1,'Ada',90000],[2,'Bo',50000],[3,'Ci',80000],[4,'Dex',70000]],
 ['name'],[['Ada'],['Ci'],['Dex']],true,
 'ORDER BY salary DESC LIMIT 3.',
 'SELECT name FROM employees ORDER BY salary DESC LIMIT 3;'],
['write-e38','easy','DISTINCT','Write a query listing every distinct color of car in the fleet.',
 'cars',['id','model','color'],[[1,'A','Red'],[2,'B','Blue'],[3,'C','Red'],[4,'D','Green']],
 ['color'],[['Red'],['Blue'],['Green']],false,
 'SELECT DISTINCT color.',
 'SELECT DISTINCT color FROM cars;'],
['write-h18','hard','CTE · JOIN · COUNT','Write a query (using WITH) which lists each buyer along with how many distinct products they have bought.',
 'buyers',['id','name'],[[1,'Ada'],[2,'Bo'],[3,'Ci']],
 'purchases',['id','buyer_id','product_id'],[[1,1,10],[2,1,10],[3,2,20],[4,1,30],[5,3,20]],
 ['name','count'],[['Ada',3],['Bo',1],['Ci',1]],false,
 'WITH counts AS (SELECT buyer_id, COUNT(DISTINCT product_id) c FROM purchases GROUP BY buyer_id) ... JOIN.',
 'WITH counts AS (SELECT buyer_id, COUNT(DISTINCT product_id) AS c FROM purchases GROUP BY buyer_id) SELECT buyers.name, counts.c AS count FROM buyers JOIN counts ON buyers.id = counts.buyer_id;'],
['write-h19','hard','LEFT JOIN · WHERE NULL','Write a query listing the names of publishers (from publishers) that have never released any book.',
 'publishers',['id','name'],[[1,'OneBook'],[2,'NoBooks'],[3,'Third']],
 'books',['id','title','publisher_id'],[[1,'X',1],[2,'Y',1],[3,'Z',3]],
 ['name'],[['NoBooks']],false,
 'LEFT JOIN books ... WHERE books.id IS NULL.',
 'SELECT publishers.name FROM publishers LEFT JOIN books ON publishers.id = books.publisher_id WHERE books.id IS NULL;'],
['write-h20','hard','GROUP BY · HAVING · COUNT','Write a query listing departments with more than 3 employees.',
 'departments',['id','name'],[[1,'Eng'],[2,'Sales'],[3,'HR']],
 'employees',['id','name','dept_id'],[[1,'A',1],[2,'B',1],[3,'C',1],[4,'D',1],[5,'E',2],[6,'F',2],[7,'G',3]],
 ['name'],[['Eng']],false,
 'GROUP BY ... HAVING COUNT(*) > 3.',
 'SELECT departments.name FROM departments JOIN employees ON departments.id = employees.dept_id GROUP BY departments.name HAVING COUNT(*) > 3;'],
]
