export const qs = [
['write-h81','hard','WINDOW · LAG','Write a query showing each month with its sales and the change from the previous month.',
 'sales',['id','month','amount'],[[1,'Jan',100],[2,'Feb',150],[3,'Mar',120],[4,'Apr',180]],
 ['month','change'],[['Jan',null],['Feb',50],['Mar',-30],['Apr',60]],true,
 'LAG(amount) OVER (ORDER BY month).',
 'SELECT month, amount - LAG(amount) OVER (ORDER BY month) AS change FROM sales;'],
['write-h82','hard','CTE · GROUP BY HAVING','Write a query (using a CTE) listing positions held by 2 or more people.',
 'positions',['id','title'],[[1,'Admin'],[2,'Dev'],[3,'Ops']],
 'people',['id','name','position_id'],[[1,'Ada',1],[2,'Bo',2],[3,'Ci',2],[4,'Dex',3]],
 ['title'],[['Dev']],false,
 'WITH counts AS ... GROUP BY position_id HAVING COUNT(*) >= 2.',
 'WITH counts AS (SELECT position_id, COUNT(*) AS c FROM people GROUP BY position_id) SELECT positions.title FROM positions JOIN counts ON counts.position_id = positions.id WHERE counts.c >= 2;'],
['write-h83','hard','HAVING · AVG','Write a query listing product categories whose average price exceeds 100.',
 'products',['id','name','category','price'],[[1,'Pen','Office',5],[2,'Desk','Office',200],[3,'Lamp','Office',150],[4,'Cup','Kitchen',25]],
 ['category'],[['Office']],false,
 'GROUP BY category HAVING AVG(price) > 100.',
 'SELECT category FROM products GROUP BY category HAVING AVG(price) > 100;'],
['write-h84','hard','JOIN · GROUP BY · COUNT','Write a query showing each store and the number of distinct products it sells.',
 'stores',['id','name'],[[1,'S1'],[2,'S2']],
 'stock',['id','store_id','product_id'],[[1,1,10],[2,1,11],[3,1,10],[4,2,20],[5,2,21],[6,2,21]],
 ['name','count'],[['S1',2],['S2',2]],false,
 'JOIN + COUNT(DISTINCT product_id).',
 'SELECT stores.name, COUNT(DISTINCT stock.product_id) AS count FROM stores JOIN stock ON stores.id = stock.store_id GROUP BY stores.name;'],
['write-h85','hard','LEFT JOIN · WHERE NULL','Write a query listing brands that appear in no order.',
 'brands',['id','name'],[[1,'A'],[2,'B'],[3,'C']],
 'orders',['id','brand_id'],[[1,1],[2,1],[3,3]],
 ['name'],[['B']],false,
 'LEFT JOIN + WHERE orders.id IS NULL.',
 'SELECT brands.name FROM brands LEFT JOIN orders ON brands.id = orders.brand_id WHERE orders.id IS NULL;'],
['write-h86','hard','UNION ALL','Write a query returning the combined list of part numbers from parts_a and parts_b.',
 'parts_a',['id','part_no'],[[1,'P1'],[2,'P2']],
 'parts_b',['id','part_no'],[[1,'P2'],[2,'P3']],
 ['part_no'],[['P1'],['P2'],['P2'],['P3']],true,
 'UNION ALL keeps duplicates.',
 'SELECT part_no FROM parts_a UNION ALL SELECT part_no FROM parts_b;'],
['write-h87','hard','SELF JOIN · AS','Write a query showing each employee and their manager\'s name (employees have a manager_id).',
 'employees',['id','name','manager_id'],[[1,'Ada',null],[2,'Bo',1],[3,'Ci',1],[4,'Dex',2]],
 ['name','manager'],[['Ada',null],['Bo','Ada'],['Ci','Ada'],['Dex','Bo']],true,
 'SELF JOIN (employees e1 JOIN employees e2 ON e1.manager_id = e2.id).',
 "SELECT e1.name, e2.name AS manager FROM employees e1 LEFT JOIN employees e2 ON e1.manager_id = e2.id;"],
