export const qs = [
['write-h21','hard','SELF JOIN','Write a query showing the name of each employee and their manager\'s name.',
 'employees',['id','name','manager_id'],[[1,'Ada',3],[2,'Bo',3],[3,'Ci',null],[4,'Dex',1]],
 ['name','manager'],[['Ada','Ci'],['Bo','Ci'],['Dex','Ada']],false,
 'SELF JOIN on employees.manager_id = manager.id.',
 'SELECT e.name, m.name AS manager FROM employees e JOIN employees m ON e.manager_id = m.id;'],
['write-h22','hard','CASE · SUM','Write a query showing total sales as total and the portion over 100 as high.',
 'sales',['id','amount'],[[1,120],[2,80],[3,200],[4,50]],
 ['total','high'],[['450','320']],false,
 'SUM(CASE WHEN amount > 100 THEN amount ELSE 0 END) AS high.',
 'SELECT SUM(amount) AS total, SUM(CASE WHEN amount > 100 THEN amount ELSE 0 END) AS high FROM sales;'],
['write-h23','hard','WITH · RANK','Write a query using a CTE with RANK to list the top salary in each department.',
 'employees',['id','name','dept','salary'],[[1,'Ada','Eng',80000],[2,'Bo','Eng',90000],[3,'Ci','Sales',50000],[4,'Dex','Sales',60000]],
 ['dept','top_salary'],[['Eng',90000],['Sales',60000]],false,
 'RANK() OVER (PARTITION BY dept ORDER BY salary DESC).',
 'WITH r AS (SELECT dept, salary, RANK() OVER (PARTITION BY dept ORDER BY salary DESC) rnk FROM employees) SELECT DISTINCT dept, salary AS top_salary FROM r WHERE rnk = 1;'],
['write-h24','hard','JOIN · GROUP BY','Write a query showing each publisher with the number of books they released.',
 'publishers',['id','name'],[[1,'One'],[2,'Two'],[3,'Zero']],
 'books',['id','title','publisher_id'],[[1,'A',1],[2,'B',1],[3,'C',2]],
 ['name','count'],[['One',2],['Two',1],['Zero',0]],false,
 'LEFT JOIN + GROUP BY + COUNT(books.id).',
 'SELECT publishers.name, COUNT(books.id) AS count FROM publishers LEFT JOIN books ON publishers.id = books.publisher_id GROUP BY publishers.name;'],
['write-h25','hard','NOT EXISTS','Write a query listing customers who have placed no orders.',
 'customers',['id','name'],[[1,'Ada'],[2,'Bo'],[3,'Ci']],
 'orders',['id','customer_id'],[[1,1],[2,3]],
 ['name'],[['Bo']],false,
 'WHERE NOT EXISTS (SELECT 1 FROM orders WHERE customer_id = customers.id).',
 'SELECT name FROM customers WHERE NOT EXISTS (SELECT 1 FROM orders WHERE customer_id = customers.id);'],
]
