export const qs = [
['write-h26','hard','UNION','Write a query returning a single list of all names from both customers and suppliers, with no duplicates.',
 'customers',[['id','name']],[[1,'Ada'],[2,'Bo']],
 'suppliers',[['id','name']],[[1,'Ci'],[2,'Bo']],
 ['name'],[['Ada'],['Bo'],['Ci']],false,
 'UNION removes duplicates (Bo appears once).',
 'SELECT name FROM customers UNION SELECT name FROM suppliers;'],
['write-h27','hard','HAVING · COUNT','Write a query showing product categories that have 2 or more products.',
 'products',['id','name','category'],[[1,'Pen','Office'],[2,'Desk','Office'],[3,'Cup','Kitchen'],[4,'Pan','Kitchen'],[5,'Bowl','Kitchen']],
 ['category'],[['Office'],['Kitchen']],false,
 'GROUP BY category HAVING COUNT(*) >= 2.',
 'SELECT category FROM products GROUP BY category HAVING COUNT(*) >= 2;'],
['write-h28','hard','SUBQUERY · ALL','Write a query returning names of products priced higher than every office product.',
 'products',['id','name','category','price'],[[1,'Pen','Office',5],[2,'Desk','Office',200],[3,'Chair','Office',100],[4,'Lamp','Home',300],[5,'Cup','Home',15]],
 ['name'],[['Lamp']],false,
 'WHERE price > ALL (SELECT price FROM products WHERE category = \'Office\').',
 'SELECT name FROM products WHERE price > ALL (SELECT price FROM products WHERE category = \'Office\');'],
['write-h29','hard','JOIN · HAVING','Write a query listing teams whose total score is above 150 (team names from teams, scores in results).',
 'teams',[['id','name']],[[1,'Reds'],[2,'Blues']],
 'results',[['id','team_id','score']],[[1,1,90],[2,1,80],[3,2,60]],
 ['name'],[['Reds']],false,
 'JOIN then GROUP BY teams.name HAVING SUM(results.score) > 150.',
 'SELECT teams.name FROM teams JOIN results ON teams.id = results.team_id GROUP BY teams.name HAVING SUM(results.score) > 150;'],
['write-h30','hard','CORRELATED · COUNT','Write a query listing authors and the number of books they wrote, using a correlated subquery (count only).',
 'authors',[['id','name']],[[1,'Ada'],[2,'Bo'],[3,'Ci']],
 'books',[['id','author_id']],[[1,1],[2,1],[3,3]],
 ['name','count'],[['Ada',2],['Bo',0],['Ci',1]],false,
 'Correlate: (SELECT COUNT(*) FROM books WHERE author_id = authors.id).',
 'SELECT authors.name, (SELECT COUNT(*) FROM books WHERE author_id = authors.id) AS count FROM authors;'],
]
