export const qs = [
['write-h71','hard','WINDOW · RANK','Write a query ranking products by price (1 = most expensive) using RANK.',
 'products',['id','name','price'],[[1,'Pen',5],[2,'Desk',300],[3,'Cup',15],[4,'Lamp',300]],
 ['name','rn'],[['Desk',1],['Lamp',1],['Cup',3],['Pen',4]],false,
 'RANK() OVER (ORDER BY price DESC) — for ties, next rank skips.',
 'SELECT name, RANK() OVER (ORDER BY price DESC) AS rn FROM products;'],
['write-h72','hard','WINDOW · SUM TOTAL','Write a query showing each product with price and the overall average price.',
 'products',['id','name','price'],[[1,'Pen',5],[2,'Desk',300],[3,'Cup',15],[4,'Lamp',80]],
 ['name','price','avg'],[['Pen',5,100],['Desk',300,100],['Cup',15,100],['Lamp',80,100]],true,
 'Use AVG(price) OVER () to repeat the overall average on every row.',
 'SELECT name, price, AVG(price) OVER () AS avg FROM products;'],
['write-h73','hard','WITH · RECURSIVE','Write a query (using WITH RECURSIVE) producing a list of numbers 1 to 4 in a column n.',
 'singleton',['dummy'],[[0]],
 ['n'],[['1'],['2'],['3'],['4']],true,
 'WITH RECURSIVE cnt(n) AS (SELECT 1 UNION ALL SELECT n + 1 FROM cnt WHERE n < 4).',
 'WITH RECURSIVE cnt(n) AS (SELECT 1 UNION ALL SELECT n + 1 FROM cnt WHERE n < 4) SELECT n FROM cnt;'],
['write-h74','hard','CTE · JOIN · WHERE NULL','Write a query listing cities with no residents.',
 'cities',['id','name'],[[1,'Aha'],[2,'Bho'],[3,'Csi']],
 'residents',['id','city_id'],[[1,1],[2,1],[3,3]],
 ['name'],[['Bho']],false,
 'LEFT JOIN residents ON cities.id = residents.city_id WHERE residents.id IS NULL.',
 'SELECT cities.name FROM cities LEFT JOIN residents ON cities.id = residents.city_id WHERE residents.id IS NULL;'],
]
