export const qs = [
['write-m1','medium','GROUP BY','Write a query showing how many employees are in each department.',
 'employees',['id','name','dept'],[[1,'Ada','Sales'],[2,'Bo','Sales'],[3,'Ci','Eng']],
 ['dept','count'],[[ 'Sales',2],['Eng',1]],false,
 'GROUP BY dept with COUNT(*).',
 'SELECT dept, COUNT(*) AS count FROM employees GROUP BY dept;'],
['write-m2','medium','GROUP BY · HAVING','Write a query listing departments with at least 2 employees.',
 'employees',['id','name','dept'],[[1,'Ada','Sales'],[2,'Bo','Sales'],[3,'Ci','Eng'],[4,'Dex','Sales']],
 ['dept'],[['Sales']],false,
 'HAVING COUNT(*) >= 2.',
 'SELECT dept FROM employees GROUP BY dept HAVING COUNT(*) >= 2;'],
['write-m3','medium','JOIN','Write a query pairing each product with the name of its supplier.',
 'products',[['id','name','supplier_id']],[[1,'Pen',1],[2,'Desk',2]],
 'suppliers',['id','name'],[[1,'NibCo'],[2,'WoodCo']],
 ['name','supplier'],[['Pen','NibCo'],['Desk','WoodCo']],false,
 'JOIN suppliers ON products.supplier_id = suppliers.id.',
 'SELECT products.name, suppliers.name AS supplier FROM products JOIN suppliers ON products.supplier_id = suppliers.id;'],
['write-m4','medium','JOIN','Write a query showing order references with the customer name for each order.',
 'orders',['id','ref','customer_id'],[[1,'A-1',1],[2,'B-2',2]],
 'customers',['id','name'],[[1,'Ada'],[2,'Bo']],
 ['ref','name'],[['A-1','Ada'],['B-2','Bo']],false,
 'JOIN customers ON orders.customer_id = customers.id.',
 'SELECT orders.ref, customers.name FROM orders JOIN customers ON orders.customer_id = customers.id;'],
['write-m5','medium','LEFT JOIN','Write a query listing every author, with the count of their books (0 if none).',
 'authors',['id','name'],[[1,'Ada'],[2,'Bo'],[3,'Ci']],
 'books',['id','title','author_id'],[[1,'X',1],[2,'Y',1],[3,'Z',3]],
 ['name','count'],[['Ada',2],['Bo',0],['Ci',1]],false,
 'LEFT JOIN books + GROUP BY.',
 'SELECT authors.name, COUNT(books.id) AS count FROM authors LEFT JOIN books ON authors.id = books.author_id GROUP BY authors.name;'],
['write-m6','medium','SUM','Write a query showing each customer\'s total order value.',
 'customers',['id','name'],[[1,'Ada'],[2,'Bo']],
 'orders',['id','customer_id','amount'],[[1,1,100],[2,1,50],[3,2,75]],
 ['name','total'],[['Ada',150],['Bo',75]],false,
 'GROUP BY + SUM(amount).',
 'SELECT customers.name, SUM(orders.amount) AS total FROM customers JOIN orders ON customers.id = orders.customer_id GROUP BY customers.name;'],
['write-m7','medium','ORDER BY · DESC','Write a query listing items heaviest first.',
 'items',['id','name','weight'],[[1,'Pen',5],[2,'Desk',300],[3,'Cup',20]],
 ['name'],[['Desk'],['Cup'],['Pen']],true,
 'ORDER BY weight DESC.',
 'SELECT name FROM items ORDER BY weight DESC;'],
['write-m8','medium','BETWEEN','Write a query showing names of employees hired in 202 renters 2020.',
 'employees',['id','name','hired'],[[1,'Ada','2020-03-01'],[2,'Bo','2021-06-01'],[3,'Ci','2020-12-01']],
 ['name'],[['Ada'],['Ci']],false,
 'WHERE hired BETWEEN \'2020-01-01\' AND \'2020-12-31\'.',
 "SELECT name FROM employees WHERE hired BETWEEN '2020-01-01' AND '2020-12-31';"],
['write-m9','medium','WHERE · NULL','Write a query listing customers who provided no phone.',
 'customers',['id','name','phone'],[[1,'Ada','555'],[2,'Bo',null],[3,'Ci',null]],
 ['name'],[['Bo'],['Ci']],false,
 'WHERE phone IS NULL.',
 'SELECT name FROM customers WHERE phone IS NULL;'],
['write-m10','medium','DISTINCT','Write a query listing every distinct category that appears in catalog.',
 'catalog',['id','item','category'],[[1,'Pen','Office'],[2,'Desk','Office'],[3,'Cup','Kitchen']],
 ['category'],[['Office'],['Kitchen']],false,
 'SELECT DISTINCT category.',
 'SELECT DISTINCT category FROM catalog;'],
['write-m11','medium','COUNT','Write a query counting how many orders exist.',
 'orders',['id','ref'],[[1,'A'],[2,'B'],[3,'C']],
 ['count'],[['3']],false,
 'SELECT COUNT(*).',
 'SELECT COUNT(*) FROM orders;'],
['write-m12','medium','MAX · MIN','Write a query showing both the max and min salary.',
 'employees',['id','name','salary'],[[1,'Ada',90000],[2,'Bo',50000],[3,'Ci',70000]],
 ['max','min'],[['90000','50000']],false,
 'MAX(salary), MIN(salary).',
 'SELECT MAX(salary) AS max, MIN(salary) AS min FROM employees;'],
['write-m13','medium','WHERE · IN','Write a query returning names of products whose id is 2, 4, or 6.',
 'products',['id','name'],[[1,'Pen'],[2,'Desk'],[3,'Cup'],[4,'Box'],[6,'Lamp']],
 ['name'],[['Desk'],['Box'],['Lamp']],false,
 'WHERE id IN (2, 4, 6).',
 'SELECT name FROM products WHERE id IN (2, 4, 6);'],
['write-m14','medium','ORDER BY · DESC · LIMIT','Write a query returning the top-2 most expensive product names.',
 'products',['id','name','price'],[[1,'Pen',5],[2,'Desk',300],[3,'Cup',10],[4,'Chair',90]],
 ['name'],[['Desk'],['Chair']],true,
 'ORDER BY price DESC LIMIT 2.',
 'SELECT name FROM products ORDER BY price DESC LIMIT 2;'],
['write-m15','medium','AS alias','Write a query showing salary doubled, labeled doubled.',
 'employees',['id','name','salary'],[[1,'Ada',50000],[2,'Bo',80000]],
 ['name','doubled'],[['Ada','100000'],['Bo','160000']],false,
 'salary * 2 AS doubled.',
 'SELECT name, salary * 2 AS doubled FROM employees;'],
]
