export const qs = [
['write-m16','medium','GROUP BY · HAVING','Write a query listing product categories that have more than 1 product.',
 'products',['id','name','category'],[[1,'Pen','Office'],[2,'Desk','Office'],[3,'Cup','Kitchen'],[4,'Bowl','Kitchen'],[5,'Pan','Kitchen']],
 ['category'],[['Kitchen']],false,
 'HAVING COUNT(*) > 1.',
 'SELECT category FROM products GROUP BY category HAVING COUNT(*) > 1;'],
['write-m17','medium','JOIN · WHERE','Write a query returning the names of books with their author names, only for authors named Ada.',
 'books',[['id','title','author_id']],[[1,'X',1],[2,'Y',2]],
 'authors',['id','name'],[[1,'Ada'],[2,'Bo']],
 ['title','author'],[['X','Ada']],false,
 'JOIN + WHERE authors.name = \'Ada\'.',
 "SELECT books.title, authors.name AS author FROM books JOIN authors ON books.author_id = authors.id WHERE authors.name = 'Ada';"],
['write-m18','medium','AVG','Write a query returning the average price of products.',
 'products',['id','name','price'],[[1,'Pen',5],[2,'Desk',15],[3,'Cup',10]],
 ['avg'],[['10']],false,
 'AVG(price) AS avg.',
 'SELECT AVG(price) AS avg FROM products;'],
['write-m19','medium','COUNT · DISTINCT','Write a query counting how many distinct categories exist.',
 'products',['id','name','category'],[[1,'Pen','Office'],[2,'Desk','Office'],[3,'Cup','Kitchen']],
 ['count'],[['2']],false,
 'COUNT(DISTINCT category).',
 'SELECT COUNT(DISTINCT category) FROM products;'],
['write-m20','medium','INNER JOIN','Write a query returning the name of every product that has been ordered (join product→orders).',
 'products',['id','name'],[[1,'Pen'],[2,'Desk'],[3,'Cup'],[4,'Lamp']],
 'orders',['id','product_id'],[[1,1],[2,3],[3,1]],
 ['name'],[['Pen'],['Desk'],['Cup']],false,
 'SELECT DISTINCT products.name ... JOIN orders.',
 'SELECT DISTINCT products.name FROM products JOIN orders ON products.id = orders.product_id;'],
['write-m21','medium','ORDER BY · LIMIT','Write a query returning the 2 oldest employee names.',
 'employees',['id','name','birth'],[[1,'Ada','2000-01-01'],[2,'Bo','1995-06-01'],[3,'Ci','1980-12-01']],
 ['name'],[['Ci'],['Bo']],true,
 'ORDER BY birth ASC LIMIT 2.',
 'SELECT name FROM employees ORDER BY birth ASC LIMIT 2;'],
['write-m22','medium','WHERE · OR','Write a query returning names of employees who work in Sales or whose salary exceeds 80000.',
 'employees',['id','name','dept','salary'],[[1,'Ada','Sales',60000],[2,'Bo','Eng',90000],[3,'Ci','Sales',70000],[4,'Dex','Eng',50000]],
 ['name'],[['Ada'],['Bo'],['Ci']],false,
 'WHERE dept = \'Sales\' OR salary > 80000.',
 'SELECT name FROM employees WHERE dept = \'Sales\' OR salary > 80000;'],
['write-m23','medium','BETWEEN · AND','Write a query showing names of products priced between 20 and 100 inclusive.',
 'products',['id','name','price'],[[1,'Pen',5],[2,'Box',20],[3,'Cup',100],[4,'Lamp',300]],
 ['name'],[['Box'],['Cup']],false,
 'WHERE price BETWEEN 20 AND 100.',
 'SELECT name FROM products WHERE price BETWEEN 20 AND 100;'],
]
