export const qs = [
['write-m24','medium','GROUP BY','Write a query showing the number of products per brand.',
 'products',['id','name','brand'],[[1,'Pen','A'],[2,'Desk','B'],[3,'Cup','A'],[4,'Lamp','B']],
 ['brand','count'],[['A',2],['B',2]],false,
 'GROUP BY brand with COUNT(*).',
 'SELECT brand, COUNT(*) AS count FROM products GROUP BY brand;'],
['write-m25','medium','SUM','Write a query showing total value of stock per warehouse.',
 'warehouses',['id','name'],[[1,'North'],[2,'South']],
 'stock',['id','warehouse_id','qty'],[[1,1,10],[2,1,5],[3,2,20]],
 ['name','total'],[['North',15],['South',20]],false,
 'JOIN + GROUP BY + SUM(qty).',
 'SELECT warehouses.name, SUM(stock.qty) AS total FROM warehouses JOIN stock ON warehouses.id = stock.warehouse_id GROUP BY warehouses.name;'],
['write-m26','medium','LEFT JOIN','Write a query showing every department, with headcount (0 if none).',
 'departments',['id','name'],[[1,'Eng'],[2,'Sales'],[3,'HR']],
 'employees',['id','name','dept_id'],[[1,'Ada',1],[2,'Bo',1],[3,'Ci',2]],
 ['name','count'],[['Eng',2],['Sales',1],['HR',0]],false,
 'LEFT JOIN + GROUP BY.',
 'SELECT departments.name, COUNT(employees.id) AS count FROM departments LEFT JOIN employees ON departments.id = employees.dept_id GROUP BY departments.name;'],
['write-m27','medium','WHERE · IN','Write a query returning names of cities in state CA or TX.',
 'cities',['id','name','state'],[[1,'LA','CA'],[2,'NY','NY'],[3,'SF','CA'],[4,'Dallas','TX'],[5,'Miami','FL']],
 ['name'],[['LA'],['SF'],['Dallas']],false,
 'WHERE state IN (\'CA\', \'TX\').',
 "SELECT name FROM cities WHERE state IN ('CA', 'TX');"],
['write-m28','medium','ORDER BY · ASC','Write a query listing student names alphabetically.',
 'students',['id','name'],[[1,'Zoe'],[2,'Ada'],[3,'Sam']],
 ['name'],[['Ada'],['Sam'],['Zoe']],true,
 'ORDER BY name ASC.',
 'SELECT name FROM students ORDER BY name ASC;'],
['write-m29','medium','HAVING','Write a query listing brands whose average price exceeds 50.',
 'products',['id','name','brand','price'],[[1,'Pen','A',40],[2,'Desk','B',200],[3,'Cup','A',60],[4,'Lamp','B',20]],
 ['brand'],[['A'],['B']],false,
 'GROUP BY brand HAVING AVG(price) > 50.',
 'SELECT brand FROM products GROUP BY brand HAVING AVG(price) > 50;'],
['write-m30','medium','JOIN · WHERE · NULL','Write a query listing names of products never assigned to any order (no matching order row).',
 'products',['id','name'],[[1,'Pen'],[2,'Desk'],[3,'Cup'],[4,'Lamp']],
 'orders',['id','product_id'],[[1,1],[2,2],[3,1]],
 ['name'],[['Desk'],['Cup'],['Lamp']],false,
 'LEFT JOIN orders ... WHERE orders.id IS NULL.',
 'SELECT products.name FROM products LEFT JOIN orders ON products.id = orders.product_id WHERE orders.id IS NULL;'],
]
export const schema_names = ['products','orders']
