export const qs = [
['write-open11','hard','WINDOW · ROW_NUMBER','Write a query showing each employee with their rank by salary (highest gets 1), using ROW_NUMBER.',
 'employees',['id','name','salary'],[[1,'Ada',90000],[2,'Bo',50000],[3,'Ci',80000]],
 ['name','rn'],[['Ada',1],['Ci',2],['Bo',3]],true,
 'ROW_NUMBER() OVER (ORDER BY salary DESC).',
 'SELECT name, ROW_NUMBER() OVER (ORDER BY salary DESC) AS rn FROM employees;'],
['write-open12','hard','CORRELATED · EXISTS','Write a query returning names of departments that currently have no employees.',
 'departments',['id','name'],[[1,'Eng'],[2,'Sales'],[3,'HR']],
 'employees',['id','name','dept_id'],[[1,'Ada',1],[2,'Bo',2]],
 ['name'],[['HR']],false,
 'WHERE NOT EXISTS correlated',
 'SELECT name FROM departments d WHERE NOT EXISTS (SELECT 1 FROM employees e WHERE e.dept_id = d.id);'],
['write-open13','hard','UNION ALL','Write a query returning a single list of all product names from both tables, keeping duplicates.',
 'products_a',['id','name'],[[1,'Pen'],[2,'Desk']],
 'products_b',['id','name'],[[2,'Desk'],[3,'Cup']],
 ['name'],[['Pen'],['Desk'],['Desk'],['Cup']],false,
 'UNION ALL keeps duplicates (Desk appears twice).',
 'SELECT name FROM products_a UNION ALL SELECT name FROM products_b;'],
['write-open14','hard','CTE · RECURSIVE','Write a query (WITH RECURSIVE) producing a CTE column n holding numbers 1 through 3.',
 '---','---','---',
 '---'],[],[],'false',
 'WITH RECURSIVE counts(n) AS (SELECT 1 UNION ALL SELECT n + 1 FROM counts WHERE n < 3) SELECT n FROM counts;'],
]
