export const qs = [
['write-h51','hard','OVER · PARTITION','Write a query listing product names with their sales and the running total of sales ordered by date.',
 'products',['id','name'],[[1,'Pen'],[2,'Desk'],[3,'Cup']],
 'sales',['id','product_id','date','qty'],[[1,1,'2024-01-01',10],[2,2,'2024-01-02',5],[3,1,'2024-01-03',7],[4,3,'2024-01-04',4]],
 ['name','date','qty','running'],[['Pen','2024-01-01',10,10],['Pen','2024-01-03',7,17],['Desk','2024-01-02',5,5],['Cup','2024-01-04',4,4]],true,
 'Window: SUM(qty) OVER (ORDER BY date).',
 'SELECT products.name, sales.date, sales.qty, SUM(sales.qty) OVER (ORDER BY sales.date) AS running FROM sales JOIN products ON sales.product_id = products.id;'],
['write-h52','hard','LAG','Write a query listing each month with its sales and the sales from the previous month.',
 'sales',['id','month','amount'],[[1,'Jan',100],[2,'Feb',150],[3,'Mar',120],[4,'Apr',180]],
 ['month','amount','prev'],[['Jan',100,null],['Feb',150,100],['Mar',120,150],['Apr',180,120]],true,
 'LAG(amount) OVER (ORDER BY month).',
 'SELECT month, amount, LAG(amount) OVER (ORDER BY month) AS prev FROM sales;'],
['write-h53','hard','CTE · COUNT · 0','Write a query (using with) showing each customer and how many orders they have, defaulting unpaid customers to 0.', 
 'customers',['id','name'],[[1,'Ada'],[2,'Bo'],[3,'Ci']],
 'orders',['id','customer_id','paid'],[[1,1,1],[2,1,1],[3,2,0]],
 ['name','count'],[['Ada',2],['Bo',0],['Ci',0]],false,
 'LEFT JOIN + COUNT(orders.id), COALESCE for 0.',
 'WITH c AS (SELECT customers.name, COUNT(orders.id) AS count FROM customers LEFT JOIN orders ON customers.id = orders.customer_id GROUP BY customers.name) SELECT name, COALESCE(count, 0) AS count FROM c;'],
['write-h54','hard','CASE · COUNT','Write a query showing each department with counts of high (salary>70000) vs not-high employees.',
 'employees',['id','name','dept','salary'],[[1,'Ada','Eng',90000],[2,'Bo','Eng',50000],[3,'Ci','Sales',40000],[4,'Dex','Sales',80000]],
 ['dept','high','not_high'],[['Eng',1,1],['Sales',1,1]],false,
 'SELECT dept, SUM(CASE WHEN salary>70000 THEN 1 ELSE 0 END) AS high, ...',
 'SELECT dept, SUM(CASE WHEN salary>70000 THEN 1 ELSE 0 END) AS high, SUM(CASE WHEN salary<=70000 THEN 1 ELSE 0 END) AS not_high FROM employees GROUP BY dept;'],
['write-h55','hard','JOIN · SUM · DISTINCT','Write a query showing each customer and the total distinct products they purchased.',
 'customers',['id','name'],[[1,'Ada'],[2,'Bo']],
 'sales',['id','customer_id','product_id','qty'],[[1,1,1,10],[2,1,2,5],[3,1,1,7],[4,2,3,4]],
 ['name','distinct_products'],[['Ada',2],['Bo',1]],false,
 'SUM over DISTINCT product via subquery per customer.',
 'SELECT customers.name, (SELECT COUNT(DISTINCT product_id) FROM sales WHERE sales.customer_id = customers.id) AS distinct_products FROM customers;'],
['write-h56','hard','ROLLUP','Write a query (using GROUP BY ROLLUP) showing total quantity per brand, plus a grand total.',
 'products',['id','brand','qty'],[[1,'A',10],[2,'B',5],[3,'A',7]],
 ['brand','total'],[['A',17],['B',5],[null,22]],true,
 'GROUP BY ROLLUP(brand) shows sub-totals then grand total.',
 'SELECT brand, SUM(qty) AS total FROM products GROUP BY ROLLUP(brand);'],
['write-h57','hard','DOUBLE JOIN','Write a query showing each product with both its supplier region and its warehouse city.',
 'products',['id','name','supplier_id','warehouse_id'],[[1,'Pen',1,1],[2,'Desk',2,2]],
 'suppliers',['id','region'],[[1,'North'],[2,'South']],
 'warehouses',['id','city'],[[1,'NYC'],[2,'LA']],
 ['name','region','city'],[['Pen','North','NYC'],['Desk','South','LA']],false,
 'Double JOIN: products JOIN suppliers AND JOIN warehouses.',
 'SELECT products.name, suppliers.region, warehouses.city FROM products JOIN suppliers ON products.supplier_id = suppliers.id JOIN warehouses ON products.warehouse_id = warehouses.id;'],
]
