export const qs = [
['write-h31','hard','GROUP BY · HAVING','Write a query (using WITH) listing years that had more than 2 sales.',
 'sales',['id','year','amount'],[[1,2020,100],[2,2020,200],[3,2021,50],[4,202 MI2,150],[5,2021,200],[6,2022,10]],
 ['year'],[['2020'],['2021']],false,
 'WITH per_year AS (SELECT year, COUNT(*) c FROM sales GROUP BY year) SELECT year FROM per_year WHERE c > 2;',
 'WITH per_year AS (SELECT year, COUNT(*) AS c FROM sales GROUP BY year) SELECT year FROM per_year WHERE c > 2;'],
['write-h32','hard','JOIN · GROUP BY · HAVING','Write a query listing customers who have placed more than 2 orders.',
 'customers',['id','name'],[[1,'Ada'],[2,'Bo'],[3,'Ci']],
 'orders',['id','customer_id'],[[1,1],[2,1],[3,1],[4,2],[5,3]],
 ['name'],[['Ada']],false,
 'JOIN then GROUP BY customers.name HAVING COUNT(*) > 2.',
 'SELECT customers.name FROM customers JOIN orders ON customers.id = orders.customer_id GROUP BY customers.name HAVING COUNT(*) > 2;'],
['write-h33','hard','CORRELATED SUBQUERY · NOT EXISTS','Write a query listing employees who have never placed an order.',
 'employees',['id','name'],[[1,'Ada'],[2,'Bo'],[3,'Ci'],[4,'Dex']],
 'orders',['id','employee_id'],[[1,1],[2,1],[3,3]],
 ['name'],[['Bo'],['Dex']],false,
 'WHERE NOT EXISTS (SELECT 1 FROM orders WHERE orders.employee_id = employees.id).',
 'SELECT name FROM employees WHERE NOT EXISTS (SELECT 1 FROM orders WHERE orders.employee_id = employees.id);'],
['write-h34','hard','SELF JOIN','Write a query listing pairs of employees who share the same manager, as (name, colleague), excluding self-pairs.',
 'employees',['id','name','manager_id'],[[1,'Ada',3],[2,'Bo',3],[3,'Ci',null],[4,'Dex',3]],
 ['name','colleague'],[['Ada','Bo'],['Ada','Dex'],['Bo','Ada'],['Bo','Dex'],['Dex','Ada'],['Dex','Bo']],false,
 'SELF JOIN: e1 JOIN employees e2 ON e1.manager_id = e2.manager_id AND e1.id < e2.id.',
 'SELECT e1.name, e2.name AS colleague FROM employees e1 JOIN employees e2 ON e1.manager_id = e2.manager_id AND e1.id < e2.id WHERE e1.manager_id IS NOT NULL;'],
['write-h35','hard','CASE · SUM','Write a query showing, per month, the count of sales that are over budget (amount > 100) as over_budget.',
 'sales',['id','month','amount'],[[1,1,120],[2,1,80],[3,2,200],[4,2,50]],
 ['month','over_budget'],[['1',1],['2',1]],false,
 'SUM(CASE WHEN amount > 100 THEN 1 ELSE 0 END) GROUP BY month.',
 'SELECT month, SUM(CASE WHEN amount > 100 THEN 1 ELSE 0 END) AS over_budget FROM sales GROUP BY month;'],
['write-h36','hard','WINDOW · RANK','Write a query showing each student with their rank by score (highest = rank 1), ordered by score descending.',
 'students',['id','name','score'],[[1,'Ada',95],[2,'Bo',95],[3,'Ci',88],[4,'Dex',70]],
 ['name','rank'],[['Ada',1],['Bo',1],['Ci',3],['Dex',4]],true,
 'RANK() OVER (ORDER BY score DESC) — ties share rank.',
 'SELECT name, RANK() OVER (ORDER BY score DESC) AS rank FROM students;'],
['write-h37','hard','RECURSIVE CTE','Write a query that produces all integers from 1 to 6 in one column n.',
 '---','none','---',
 [],[],false,'---',
 'WITH RECURSIVE seq(n) AS (SELECT 1 UNION ALL SELECT n + 1 FROM seq WHERE n < 6) SELECT n FROM seq;'],
]
