export const qs = [
['write-h61','hard','ROWS BETWEEN · WINDOW','Write a query showing each sale date with its running 2-day total of sales.',
 'sales',['id','date','amount'],[[1,'2024-01-01',100],[2,'2024-01-02',150],[3,'2024-01-03',120],[4,'2024-01-04',80]],
 ['date','running'],[['2024-01-01',100],['2024-01-02',250],['2024-01-03',270],['2024-01-04',200]],true,
 'SUM(amount) OVER (ORDER BY date ROWS BETWEEN 1 PRECEDING AND CURRENT ROW).',
 'SELECT date, SUM(amount) OVER (ORDER BY date ROWS BETWEEN 1 PRECEDING AND CURRENT ROW) AS running FROM sales;'],
['write-h62','hard','DENSE_RANK · TOP N','Write a query returning the 2 highest-paid employees using DENSE_RANK, ordered from highest.',
 'employees',['id','name','salary'],[[1,'Ada',90000],[2,'Bo',50000],[3,'Ci',90000],[4,'Dex',70000]],
 ['name'],[['Ada'],['Ci'],['Dex']],true,
 'DENSE_RANK() OVER (ORDER BY salary DESC) then filter rn <= 2 (DENSE_RANK skips no ranks for ties, so Ada & Ci both rank 1, Dex ranks 2 = 3 rows).',
 'WITH r AS (SELECT name, DENSE_RANK() OVER (ORDER BY salary DESC) AS rn FROM employees) SELECT name FROM r WHERE rn <= 2;'],
['write-h63','hard','LAG · DIFF','Write a query showing each month with its sales and the change compared to the previous month.',
 'sales',['id','month','amount'],[[1,'Jan',100],[2,'Feb',150],[3,'Mar',120]],
 ['month','amount','change'],[['Jan',100,null],['Feb',150,50],['Mar',120,-30]],false,
 'LAG(amount) + amount - LAG.',
 'SELECT month, amount, amount - LAG(amount) OVER (ORDER BY month) AS change FROM sales;'],
['write-h64','hard','CTE · JOIN · SUM','Write a query (using a CTE) listing customers whose total order value is above 150.',
 'customers',['id','name'],[[1,'Ada'],[2,'Bo'],[3,'Ci']],
 'orders',['id','customer_id','amount'],[[1,1,100],[2,1,80],[3,2,50],[4,3,200]],
 ['name'],[['Ada'],['Ci']],false,
 'WITH totals AS (SELECT customer_id, SUM(amount) t FROM orders GROUP BY customer_id) ... WHERE t > 150.',
 'WITH totals AS (SELECT customer_id, SUM(amount) AS t FROM orders GROUP BY customer_id) SELECT customers.name FROM customers JOIN totals ON customers.id = totals.customer_id WHERE totals.t > 150;'],
['write-h65','hard','CROSS JOIN','Write a query pairing every size with every color (all combinations).',
 'sizes',['id','size'],[[1,'S'],[2,'M'],[3,'L']],
 'colors',['id','color'],[[1,'Red'],[2,'Blue']],
 ['size','color'],[['S','Red'],['S','Blue'],['M','Red'],['M','Blue'],['L','Red'],['L','Blue']],true,
 'CROSS JOIN pairs each row of sizes with each row of colors.',
 'SELECT sizes.size, colors.color FROM sizes CROSS JOIN colors;'],
['write-h66','hard','GROUP BY · ROLLUP','Write a query using ROLLUP to show count of products per brand, plus a grand total row.',
 'products',['id','name','brand'],[[1,'Pen','A'],[2,'Desk','B'],[3,'Cup','A'],[4,'Bowl','B']],
 ['brand','count'],[['A',2],['B',2],[null,4]],true,
 'GROUP BY ROLLUP(brand) adds a grand-total row (brand NULL).',
 'SELECT brand, COUNT(*) AS count FROM products GROUP BY ROLLUP(brand);'],
['write-h67','hard','CTE · NOT IN','Write a query returning supplier names that appear in no purchase.',
 'suppliers',['id','name'],[[1,'NibCo'],[2,'PaperCo'],[3,'WoodCo']],
 'purchases',['id','supplier_id'],[[1,1],[2,3]],
 ['name'],[['PaperCo']],false,
 'WHERE id NOT IN (SELECT supplier_id FROM purchases).',
 'SELECT name FROM suppliers WHERE id NOT IN (SELECT supplier_id FROM purchases);'],
]
